apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jt4xrv1sg-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-1e3289df4d.nvvn.p3.openshiftapps.com/rhtap/rhtap-qe:d4865259d342ce44af224b40be8a181468b2e5e2@sha256:e977b158fca3c5896e4af4740ca42ceafa77a24f2be30f8e683820343b9e566b
          name: container-image
